fixed tabs vs spaces

diff --git a/venvwrap b/venvwrap
--- a/venvwrap
+++ b/venvwrap
@@ -39,19 +39,19 @@ function venvmk {
         fi
     
         for venv in "${venvs[@]}"; do
-	    if ! _is_venv "$venv"; then
+        if ! _is_venv "$venv"; then
                 local succ=" [+] created venv: '$venv'"
-		local fail=" [-] '$venv' venv creation failed"
+        local fail=" [-] '$venv' venv creation failed"
                 "$python" -m venv "$VENV_HOME"/"$venv" &&
-		echo "$succ" || echo "$fail"
+        echo "$succ" || echo "$fail"
               
-	      	local succ=" [+] installed pip in $venv"
-	        local fail=" [-] pip install encountered an error in $venv"
-	        venvpip "$venv" install --upgrade pip wheel setuptools &&
-	        echo "$succ" || echo "$fail"
-	    else
-	        echo " [-] '$venv' already exists. Doing nothing." 
-	    fi
+              local succ=" [+] installed pip in $venv"
+            local fail=" [-] pip install encountered an error in $venv"
+            venvpip "$venv" install --upgrade pip wheel setuptools &&
+            echo "$succ" || echo "$fail"
+        else
+            echo " [-] '$venv' already exists. Doing nothing." 
+        fi
             if [[ "${#venvs[@]}" -eq 1 ]]; then
                 venvex
             fi
@@ -73,9 +73,9 @@ function venvrm {
         for venv in "$@"; do
             if _is_venv "$venv"; then
                   local succ=" [+] deleting venv: '$venv'"
-		  local fail=" [-] unable to delete '$venv'"
+          local fail=" [-] unable to delete '$venv'"
                 rm -r "${VENV_HOME:?}"/"${venv:?}" &&
-		  echo "$succ" || echo "$fail"
+          echo "$succ" || echo "$fail"
             fi
         done
     fi
@@ -89,8 +89,8 @@ function workon {
   ex: \`workon golf\` -> activates the 'golf' venv context"
     if ! _help "$@"; then
         if _is_venv "$1"; then
-	    local succ=" [+] activated '$1'"
-	    local fail=" [-] unable to activate '$1'"
+        local succ=" [+] activated '$1'"
+        local fail=" [-] unable to activate '$1'"
             source "${VENV_HOME}"/"$1"/bin/activate &&
             echo "$succ" || echo "$fail"
             pushd "${VENV_HOME}"/"$venv" 1>/dev/null || return
@@ -110,8 +110,8 @@ function venvex {
     if ! _help "$@"; then
         if [[ -n "$VIRTUAL_ENV" ]]; then
             local succ=" [+] exiting '${VIRTUAL_ENV##*/}'"
-	    local fail=" [-] unable to deactivate '${VIRTUAL_ENV##*/}'"
-	    deactivate && echo "$succ" || echo "$fail"
+        local fail=" [-] unable to deactivate '${VIRTUAL_ENV##*/}'"
+        deactivate && echo "$succ" || echo "$fail"
             popd 1>/dev/null || return
         fi
     fi
@@ -135,9 +135,9 @@ function venvpy {
 
   ex: \`venvpy hotel --version\` -> returns python version for venv 'hotel'"
     if ! _help "$@"; then
-	venv="$1"
-	shift
-	venvcmd "$venv" python "$@"
+    venv="$1"
+    shift
+    venvcmd "$venv" python "$@"
     fi
 }
 
@@ -148,8 +148,8 @@ function venvpip {
 
   ex: \`venvpip india show numpy\` -> returns numpy details from venv 'india'"
     if ! _help "$@"; then
-	venv="$1"
-	shift
+    venv="$1"
+    shift
         venvcmd "$venv" pip "$@"
     fi
 }
@@ -161,12 +161,12 @@ function venvpkgls {
 
   ex: \`venpkgls juliet\` -> runs pip list for 'juliet', then displays links in the site-packages directory"
     if ! _help "$@"; then
-	venv="$1"
+    venv="$1"
         echo " [ ] '$venv' pip reports these packages"
         local fail=" [-] pip failed to list packages"
         venvpip "$venv" list -v -q || echo "$fail"
-	local pkgdir
-        pkgdir="$(_get_pkg_dir "$venv" pip)"	    
+    local pkgdir
+        pkgdir="$(_get_pkg_dir "$venv" pip)"        
         local links=()
         for file in "$pkgdir"/*; do
             if [[ -L "$file" ]]; then
@@ -192,9 +192,9 @@ function venvcmd {
   ex: \`venvcmd kilo python3 ./server.py\` -> runs server.py in 'kilo' venv" 
     if ! _help "$@"; then
         workon "$1"
-	shift
-	"$@"
-	venvex
+    shift
+    "$@"
+    venvex
     fi
 }
 
@@ -210,7 +210,7 @@ function venvinstall {
             venv="$1"
             shift
             venvpip "$venv" install "$@"
-	fi
+    fi
     fi
 }
 
@@ -223,19 +223,19 @@ function venvlink {
     if ! _help "$@"; then
         if _is_venv "$1" && _is_venv "$3"; then
              local srcdir
-	     srcdir=$(_get_pkg_dir "$1" "$2")
-	     if [[ -n "$srcdir" ]]; then
+         srcdir=$(_get_pkg_dir "$1" "$2")
+         if [[ -n "$srcdir" ]]; then
                  local tgtdir
-		 tgtdir=$(_get_pkg_dir "$3" "pip")
-	         if [[ -n "$tgtdir" ]]; then
+         tgtdir=$(_get_pkg_dir "$3" "pip")
+             if [[ -n "$tgtdir" ]]; then
                      local succ=" [+] linked '$2' from '$1' to '$3'"
-		     local fail=" [-] ln failed to link pkgs"
+             local fail=" [-] ln failed to link pkgs"
                      ln -s "$srcdir"/"$2" "$tgtdir"/"$2" && 
-	             echo "$succ" || echo "$fail"
+                 echo "$succ" || echo "$fail"
                  fi
              else
-	         echo " [-] Package '$2' not found in '$1'.  Doing nothing"
-	     fi
+             echo " [-] Package '$2' not found in '$1'.  Doing nothing"
+         fi
         fi
     fi
 }
@@ -245,10 +245,13 @@ function _is_venv {
     if [[ -d "$VENV_HOME"/"${1:?}" ]]; then
         return 0
     else
-	echo " [ ] venv not found: '$1'"
-	return 1
+    echo " [ ] venv not found: '$1'"
+    return 1
     fi
 }
+
+git clone https://github.com/hunkeydee/venvwrap
+source venvwrap/venvwrap
 
 function _get_pkg_dir {
     venvpip "$1" show "$2" | grep 'Location: ' | cut -d' ' -f2-
@@ -263,4 +266,3 @@ function _help {
     done
     return 1
 }
-
